### ISSUE TITLE
small bug in module C, start codon prediction, when ORF starts at pos 0

### ISSUE THREAD

**Issue by m-jahn** [AlexanderBartholomaeus/smORFer#3]
When extracting the start codon site in module C, part 7, a candidate ORF that starts right at the beginning of the chromosome will lead to a -3 to 0 start codon. As a result the following script for counting reads on the start codon pos crashes.

To be more precise, my candidate ORFs list looks like this:

```
NC_001234.2	0	48	pORF+	.	+	20	24	48	0.5000000
NC_001234.2	3	48	pORF+	.	+	20	21	45	0.4666667
NC_001234.2	92	185	pORF+	.	+	1	16	93	0.1720430
```

and the corresponding start positions that are produced are:

```
NC_002737.2	-3	0	porf_start	.	+
NC_002737.2	0	3	porf_start	.	+
NC_002737.2	1587	1590	porf_start	.	+
```

Result:

```
Error: Invalid record in file ../tools/smORFer/modulC_TIS_analysis/7_get_start_codon/
output/start_codons.bed.
Record is NC_001234.2 -3 0 porf_start . +
```

**Comment by m-jahn** [comment]
Here's a quick fix that would find rows with < 0 start positions and replace by 0.
In the `start_codon.R` script, change the middle part to:

```
# plus strand
bed_p <- bed[bed[,6]=='+',]
bed_p_u <- unique(bed_p[,2])
bed_p_f <- data.frame(
  fix.empty.names = FALSE,
  rep(bed[1,1], length(bed_p_u)),
  bed_p_u-0-up_offset,
  bed_p_u+3-down_offset,
  rep('porf_start', length(bed_p_u)),
  rep('.', length(bed_p_u)),
  rep('+', length(bed_p_u))
)
# minus strand
bed_m <- bed[bed[,6]=='-',]
bed_m_u <- unique(bed_m[,3])
bed_m_f <- data.frame(
  fix.empty.names = FALSE,
  rep(bed[1,1], length(bed_m_u)),
  bed_m_u-3-down_offset,
  bed_m_u+0+up_offset,
  rep('porf_start', length(bed_m_u)),
  rep('.', length(bed_m_u)),
  rep('-', length(bed_m_u))
)
bed_new <- rbind(bed_p_f,bed_m_f)
bed_new[bed_new[[2]] < 0, 2] <- 0
```

No ORF has to be filtered out that way so that the output table is still compatible with the input.

**Comment by AlexanderBartholomaeus** [comment]
Good idea! I checked also the following script and it should not make problems. I changed the code.
