### ISSUE TITLE
reverse-oriented start codon windows are 3 times larger than forward windows

### ISSUE THREAD

**Issue by m-jahn** [AlexanderBartholomaeus/smORFer#4]
Hi,
I noticed a difference in the size of the start codon windows when running module C, TIS analysis.
When finding start codons, forward looking ORFs get a start codon window assigned with width 3, but reverse oriented ORFs a window of 9 nt. Maybe I misunderstood something here, but from what I understand both forward and reverse ORF start windows should be the same size.

Output from `smORFer/modulC_TIS_analysis/7_get_start_codon`:

```
NC_001234.2	1663659	1663662	porf_start	.	+
NC_001234.2	1849232	1849235	porf_start	.	+
NC_001234.2	1811980	1811989	porf_start	.	-
NC_001234.2	1811965	1811974	porf_start	.	-
```

Note the difference in size. This propagates further to the results of part 8:

```
NC_001234.2	1663659	1663662	porf_start	.	+	42	3	3	1.0
NC_001234.2	1849232	1849235	porf_start	.	+	10	3	3	1.0
NC_001234.2	1811980	1811989	porf_start	.	-	16	4	9	0.4444444
NC_001234.2	1811965	1811974	porf_start	.	-	7	3	9	0.3333333
```

The coverage (last column) is of course influenced by the larger window, giving reverse ORFs probably higher counts but lower overall coverage. This can not be intended, right?

**Comment by m-jahn** [comment]
I think there's a bug in the `start_codon.R` script.
In this section

```
# plus strand
bed_p <- bed[bed[,6]=='+',]
bed_p_u <- unique(bed_p[,2])
bed_p_f <- cbind(
  rep(bed[1,1], length(bed_p_u)),
  bed_p_u-0-up_offset,
  bed_p_u+3-down_offset,
  rep('porf_start', length(bed_p_u)),
  rep('.', length(bed_p_u)),
  rep('+', length(bed_p_u))
)
```

... it should be `  bed_p_u+3+down_offset,`

**Comment by AlexanderBartholomaeus** [comment]
Your are right!! Would you like to fix errors or do some development on the project directly?

**Comment by m-jahn** [comment]
Hi Alex, yes I can fix this and start a pull request.
Thanks for your invitation to collaborate. Maybe it's not necessary to do more fixes.

**Comment by m-jahn** [comment]
I made a PR that fixes this. You can merge it and it will automatically resolve this issue here.
